name = "midas_sdk"
version = "0.5.1"
target = "javascript"

description = "A bag of SDK's that can be used with midas."
licences = ["Apache-2.0"]
repository = { type = "github", user = "midas-framework", repo = "midas_sdk" }
links = [{ title = "midas", href = "https://github.com/midas-framework/midas" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_http = ">= 3.7.0 and < 5.0.0"
midas = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 1.0.0 and < 4.0.0"
snag = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
