import gleam/io
import oas/generator
import snag

pub fn main() {
  case
    generator.build("./priv/github.openapi.json", ".", "github_sdk", [
      "meta/root", "security-advisories/list-global-advisories",
      "security-advisories/get-global-advisory", "apps/get-authenticated",
      "apps/create-from-manifest", "apps/get-webhook-config-for-app",
      "apps/update-webhook-config-for-app", "apps/list-webhook-deliveries",
      "apps/get-webhook-delivery", "apps/redeliver-webhook-delivery",
      "apps/list-installation-requests-for-authenticated-app",
      "apps/list-installations", "apps/get-installation",
      "apps/delete-installation", "apps/create-installation-access-token",
      "apps/suspend-installation", "apps/unsuspend-installation",
      "apps/delete-authorization", "apps/check-token", "apps/reset-token",
      "apps/delete-token", "apps/scope-token", "apps/get-by-slug",
      "classroom/get-an-assignment",
      "classroom/list-accepted-assignments-for-an-assignment",
      "classroom/get-assignment-grades", "classroom/list-classrooms",
      "classroom/get-a-classroom", "classroom/list-assignments-for-a-classroom",
      "codes-of-conduct/get-all-codes-of-conduct",
      "codes-of-conduct/get-conduct-code", "emojis/get",
      "copilot/list-copilot-seats-for-enterprise",
      "copilot/copilot-metrics-for-enterprise",
      "copilot/usage-metrics-for-enterprise",
      "dependabot/list-alerts-for-enterprise",
      "secret-scanning/list-alerts-for-enterprise",
      "copilot/copilot-metrics-for-enterprise-team",
      "copilot/usage-metrics-for-enterprise-team", "activity/list-public-events",
      "activity/get-feeds", "gists/list", "gists/create", "gists/list-public",
      "gists/list-starred", "gists/get", "gists/update", "gists/delete",
      "gists/list-comments", "gists/create-comment", "gists/get-comment",
      "gists/update-comment", "gists/delete-comment", "gists/list-commits",
      "gists/list-forks", "gists/fork", "gists/check-is-starred", "gists/star",
      "gists/unstar", "gists/get-revision", "gitignore/get-all-templates",
      "gitignore/get-template", "apps/list-repos-accessible-to-installation",
      "apps/revoke-installation-access-token", "issues/list",
      "licenses/get-all-commonly-used", "licenses/get", "markdown/render",
      "markdown/render-raw", "apps/get-subscription-plan-for-account",
      "apps/list-plans", "apps/list-accounts-for-plan",
      "apps/get-subscription-plan-for-account-stubbed",
      "apps/list-plans-stubbed", "apps/list-accounts-for-plan-stubbed",
      "meta/get", "activity/list-public-events-for-repo-network",
      "activity/list-notifications-for-authenticated-user",
      "activity/mark-notifications-as-read", "activity/get-thread",
      "activity/mark-thread-as-read", "activity/mark-thread-as-done",
      "activity/get-thread-subscription-for-authenticated-user",
      "activity/set-thread-subscription", "activity/delete-thread-subscription",
      "meta/get-octocat", "orgs/list", "orgs/get", "orgs/update", "orgs/delete",
      "actions/get-actions-cache-usage-for-org",
      "actions/get-actions-cache-usage-by-repo-for-org",
      "oidc/get-oidc-custom-sub-template-for-org",
      "oidc/update-oidc-custom-sub-template-for-org",
      "actions/get-github-actions-permissions-organization",
      "actions/set-github-actions-permissions-organization",
      "actions/list-selected-repositories-enabled-github-actions-organization",
      "actions/set-selected-repositories-enabled-github-actions-organization",
      "actions/enable-selected-repository-github-actions-organization",
      "actions/disable-selected-repository-github-actions-organization",
      "actions/get-allowed-actions-organization",
      "actions/set-allowed-actions-organization",
      "actions/get-github-actions-default-workflow-permissions-organization",
      "actions/set-github-actions-default-workflow-permissions-organization",
      "actions/list-self-hosted-runner-groups-for-org",
      "actions/create-self-hosted-runner-group-for-org",
      "actions/get-self-hosted-runner-group-for-org",
      "actions/update-self-hosted-runner-group-for-org",
      "actions/delete-self-hosted-runner-group-from-org",
      "actions/list-repo-access-to-self-hosted-runner-group-in-org",
      "actions/set-repo-access-to-self-hosted-runner-group-in-org",
      "actions/add-repo-access-to-self-hosted-runner-group-in-org",
      "actions/remove-repo-access-to-self-hosted-runner-group-in-org",
      "actions/list-self-hosted-runners-in-group-for-org",
      "actions/set-self-hosted-runners-in-group-for-org",
      "actions/add-self-hosted-runner-to-group-for-org",
      "actions/remove-self-hosted-runner-from-group-for-org",
      "actions/list-self-hosted-runners-for-org",
      "actions/list-runner-applications-for-org",
      "actions/generate-runner-jitconfig-for-org",
      "actions/create-registration-token-for-org",
      "actions/create-remove-token-for-org",
      "actions/get-self-hosted-runner-for-org",
      "actions/delete-self-hosted-runner-from-org",
      "actions/list-labels-for-self-hosted-runner-for-org",
      "actions/add-custom-labels-to-self-hosted-runner-for-org",
      "actions/set-custom-labels-for-self-hosted-runner-for-org",
      "actions/remove-all-custom-labels-from-self-hosted-runner-for-org",
      "actions/remove-custom-label-from-self-hosted-runner-for-org",
      "actions/list-org-secrets", "actions/get-org-public-key",
      "actions/get-org-secret", "actions/create-or-update-org-secret",
      "actions/delete-org-secret", "actions/list-selected-repos-for-org-secret",
      "actions/set-selected-repos-for-org-secret",
      "actions/add-selected-repo-to-org-secret",
      "actions/remove-selected-repo-from-org-secret",
      "actions/list-org-variables", "actions/create-org-variable",
      "actions/get-org-variable", "actions/update-org-variable",
      "actions/delete-org-variable",
      "actions/list-selected-repos-for-org-variable",
      "actions/set-selected-repos-for-org-variable",
      "actions/add-selected-repo-to-org-variable",
      "actions/remove-selected-repo-from-org-variable", "orgs/list-attestations",
      "orgs/list-blocked-users", "orgs/check-blocked-user", "orgs/block-user",
      "orgs/unblock-user", "code-scanning/list-alerts-for-org",
      "code-security/get-configurations-for-org",
      "code-security/create-configuration",
      "code-security/get-default-configurations",
      "code-security/detach-configuration", "code-security/get-configuration",
      "code-security/update-configuration", "code-security/delete-configuration",
      "code-security/attach-configuration",
      "code-security/set-configuration-as-default",
      "code-security/get-repositories-for-configuration",
      "codespaces/list-in-organization", "codespaces/set-codespaces-access",
      "codespaces/set-codespaces-access-users",
      "codespaces/delete-codespaces-access-users", "codespaces/list-org-secrets",
      "codespaces/get-org-public-key", "codespaces/get-org-secret",
      "codespaces/create-or-update-org-secret", "codespaces/delete-org-secret",
      "codespaces/list-selected-repos-for-org-secret",
      "codespaces/set-selected-repos-for-org-secret",
      "codespaces/add-selected-repo-to-org-secret",
      "codespaces/remove-selected-repo-from-org-secret",
      "copilot/get-copilot-organization-details", "copilot/list-copilot-seats",
      "copilot/add-copilot-seats-for-teams",
      "copilot/cancel-copilot-seat-assignment-for-teams",
      "copilot/add-copilot-seats-for-users",
      "copilot/cancel-copilot-seat-assignment-for-users",
      "copilot/copilot-metrics-for-organization",
      "copilot/usage-metrics-for-org", "dependabot/list-alerts-for-org",
      "dependabot/list-org-secrets", "dependabot/get-org-public-key",
      "dependabot/get-org-secret", "dependabot/create-or-update-org-secret",
      "dependabot/delete-org-secret",
      "dependabot/list-selected-repos-for-org-secret",
      "dependabot/set-selected-repos-for-org-secret",
      "dependabot/add-selected-repo-to-org-secret",
      "dependabot/remove-selected-repo-from-org-secret",
      "packages/list-docker-migration-conflicting-packages-for-organization",
      "activity/list-public-org-events", "orgs/list-failed-invitations",
      "orgs/list-webhooks", "orgs/create-webhook", "orgs/get-webhook",
      "orgs/update-webhook", "orgs/delete-webhook",
      "orgs/get-webhook-config-for-org", "orgs/update-webhook-config-for-org",
      "orgs/list-webhook-deliveries", "orgs/get-webhook-delivery",
      "orgs/redeliver-webhook-delivery", "orgs/ping-webhook",
      "api-insights/get-route-stats-by-actor", "api-insights/get-subject-stats",
      "api-insights/get-summary-stats", "api-insights/get-summary-stats-by-user",
      "api-insights/get-summary-stats-by-actor", "api-insights/get-time-stats",
      "api-insights/get-time-stats-by-user",
      "api-insights/get-time-stats-by-actor", "api-insights/get-user-stats",
      "apps/get-org-installation", "orgs/list-app-installations",
      "interactions/get-restrictions-for-org",
      "interactions/set-restrictions-for-org",
      "interactions/remove-restrictions-for-org",
      "orgs/list-pending-invitations", "orgs/create-invitation",
      "orgs/cancel-invitation", "orgs/list-invitation-teams",
      "issues/list-for-org", "orgs/list-members",
      "orgs/check-membership-for-user", "orgs/remove-member",
      "codespaces/get-codespaces-for-user-in-org",
      "codespaces/delete-from-organization", "codespaces/stop-in-organization",
      "copilot/get-copilot-seat-details-for-user",
      "orgs/get-membership-for-user", "orgs/set-membership-for-user",
      "orgs/remove-membership-for-user", "migrations/list-for-org",
      "migrations/start-for-org", "migrations/get-status-for-org",
      "migrations/download-archive-for-org", "migrations/delete-archive-for-org",
      "migrations/unlock-repo-for-org", "migrations/list-repos-for-org",
      "orgs/list-org-roles", "orgs/revoke-all-org-roles-team",
      "orgs/assign-team-to-org-role", "orgs/revoke-org-role-team",
      "orgs/revoke-all-org-roles-user", "orgs/assign-user-to-org-role",
      "orgs/revoke-org-role-user", "orgs/get-org-role",
      "orgs/list-org-role-teams", "orgs/list-org-role-users",
      "orgs/list-outside-collaborators",
      "orgs/convert-member-to-outside-collaborator",
      "orgs/remove-outside-collaborator",
      "packages/list-packages-for-organization",
      "packages/get-package-for-organization", "packages/delete-package-for-org",
      "packages/restore-package-for-org",
      "packages/get-all-package-versions-for-package-owned-by-org",
      "packages/get-package-version-for-organization",
      "packages/delete-package-version-for-org",
      "packages/restore-package-version-for-org", "orgs/list-pat-grant-requests",
      "orgs/review-pat-grant-requests-in-bulk", "orgs/review-pat-grant-request",
      "orgs/list-pat-grant-request-repositories", "orgs/list-pat-grants",
      "orgs/update-pat-accesses", "orgs/update-pat-access",
      "orgs/list-pat-grant-repositories", "projects/list-for-org",
      "projects/create-for-org", "orgs/get-all-custom-properties",
      "orgs/create-or-update-custom-properties", "orgs/get-custom-property",
      "orgs/create-or-update-custom-property", "orgs/remove-custom-property",
      "orgs/list-custom-properties-values-for-repos",
      "orgs/create-or-update-custom-properties-values-for-repos",
      "orgs/list-public-members", "orgs/check-public-membership-for-user",
      "orgs/set-public-membership-for-authenticated-user",
      "orgs/remove-public-membership-for-authenticated-user",
      // "repos/list-for-org", 
      "repos/create-in-org", "repos/get-org-rulesets",
      "repos/create-org-ruleset", "repos/get-org-rule-suites",
      "repos/get-org-rule-suite", "repos/get-org-ruleset",
      "repos/update-org-ruleset", "repos/delete-org-ruleset",
      "secret-scanning/list-alerts-for-org",
      "security-advisories/list-org-repository-advisories",
      "orgs/list-security-manager-teams", "orgs/add-security-manager-team",
      "orgs/remove-security-manager-team",
      "billing/get-github-actions-billing-org",
      "billing/get-github-packages-billing-org",
      "billing/get-shared-storage-billing-org",
      "copilot/copilot-metrics-for-team", "copilot/usage-metrics-for-team",
      "teams/list", "teams/create", "teams/get-by-name", "teams/update-in-org",
      "teams/delete-in-org", "teams/list-discussions-in-org",
      "teams/create-discussion-in-org", "teams/get-discussion-in-org",
      "teams/update-discussion-in-org", "teams/delete-discussion-in-org",
      "teams/list-discussion-comments-in-org",
      "teams/create-discussion-comment-in-org",
      "teams/get-discussion-comment-in-org",
      "teams/update-discussion-comment-in-org",
      "teams/delete-discussion-comment-in-org",
      "reactions/list-for-team-discussion-comment-in-org",
      "reactions/create-for-team-discussion-comment-in-org",
      "reactions/delete-for-team-discussion-comment",
      "reactions/list-for-team-discussion-in-org",
      "reactions/create-for-team-discussion-in-org",
      "reactions/delete-for-team-discussion",
      "teams/list-pending-invitations-in-org", "teams/list-members-in-org",
      "teams/get-membership-for-user-in-org",
      "teams/add-or-update-membership-for-user-in-org",
      "teams/remove-membership-for-user-in-org", "teams/list-projects-in-org",
      "teams/check-permissions-for-project-in-org",
      "teams/add-or-update-project-permissions-in-org",
      "teams/remove-project-in-org", "teams/list-repos-in-org",
      "teams/check-permissions-for-repo-in-org",
      "teams/add-or-update-repo-permissions-in-org", "teams/remove-repo-in-org",
      "teams/list-child-in-org",
      "orgs/enable-or-disable-security-product-on-all-org-repos",
      "projects/get-card", "projects/update-card", "projects/delete-card",
      "projects/move-card", "projects/get-column", "projects/update-column",
      "projects/delete-column", "projects/list-cards", "projects/create-card",
      "projects/move-column", "projects/get", "projects/update",
      "projects/delete", "projects/list-collaborators",
      "projects/add-collaborator", "projects/remove-collaborator",
      "projects/get-permission-for-user", "projects/list-columns",
      "projects/create-column", "rate-limit/get", "repos/get", "repos/update",
      "repos/delete", "actions/list-artifacts-for-repo", "actions/get-artifact",
      "actions/delete-artifact", "actions/download-artifact",
      "actions/get-actions-cache-usage", "actions/get-actions-cache-list",
      "actions/delete-actions-cache-by-key",
      "actions/delete-actions-cache-by-id", "actions/get-job-for-workflow-run",
      "actions/download-job-logs-for-workflow-run",
      "actions/re-run-job-for-workflow-run",
      "actions/get-custom-oidc-sub-claim-for-repo",
      "actions/set-custom-oidc-sub-claim-for-repo",
      "actions/list-repo-organization-secrets",
      "actions/list-repo-organization-variables",
      "actions/get-github-actions-permissions-repository",
      "actions/set-github-actions-permissions-repository",
      "actions/get-workflow-access-to-repository",
      "actions/set-workflow-access-to-repository",
      "actions/get-allowed-actions-repository",
      "actions/set-allowed-actions-repository",
      "actions/get-github-actions-default-workflow-permissions-repository",
      "actions/set-github-actions-default-workflow-permissions-repository",
      "actions/list-self-hosted-runners-for-repo",
      "actions/list-runner-applications-for-repo",
      "actions/generate-runner-jitconfig-for-repo",
      "actions/create-registration-token-for-repo",
      "actions/create-remove-token-for-repo",
      "actions/get-self-hosted-runner-for-repo",
      "actions/delete-self-hosted-runner-from-repo",
      "actions/list-labels-for-self-hosted-runner-for-repo",
      "actions/add-custom-labels-to-self-hosted-runner-for-repo",
      "actions/set-custom-labels-for-self-hosted-runner-for-repo",
      "actions/remove-all-custom-labels-from-self-hosted-runner-for-repo",
      "actions/remove-custom-label-from-self-hosted-runner-for-repo",
      "actions/list-workflow-runs-for-repo", "actions/get-workflow-run",
      "actions/delete-workflow-run", "actions/get-reviews-for-run",
      "actions/approve-workflow-run", "actions/list-workflow-run-artifacts",
      "actions/get-workflow-run-attempt",
      "actions/list-jobs-for-workflow-run-attempt",
      "actions/download-workflow-run-attempt-logs",
      "actions/cancel-workflow-run", "actions/review-custom-gates-for-run",
      "actions/force-cancel-workflow-run", "actions/list-jobs-for-workflow-run",
      "actions/download-workflow-run-logs", "actions/delete-workflow-run-logs",
      "actions/get-pending-deployments-for-run",
      "actions/review-pending-deployments-for-run", "actions/re-run-workflow",
      "actions/re-run-workflow-failed-jobs", "actions/get-workflow-run-usage",
      "actions/list-repo-secrets", "actions/get-repo-public-key",
      "actions/get-repo-secret", "actions/create-or-update-repo-secret",
      "actions/delete-repo-secret", "actions/list-repo-variables",
      "actions/create-repo-variable", "actions/get-repo-variable",
      "actions/update-repo-variable", "actions/delete-repo-variable",
      "actions/list-repo-workflows", "actions/get-workflow",
      "actions/disable-workflow", "actions/create-workflow-dispatch",
      "actions/enable-workflow", "actions/list-workflow-runs",
      "actions/get-workflow-usage", "repos/list-activities",
      "issues/list-assignees", "issues/check-user-can-be-assigned",
      "repos/create-attestation", "repos/list-attestations",
      "repos/list-autolinks", "repos/create-autolink", "repos/get-autolink",
      "repos/delete-autolink", "repos/check-automated-security-fixes",
      "repos/enable-automated-security-fixes",
      "repos/disable-automated-security-fixes", "repos/list-branches",
      "repos/get-branch", "repos/get-branch-protection",
      "repos/update-branch-protection", "repos/delete-branch-protection",
      "repos/get-admin-branch-protection", "repos/set-admin-branch-protection",
      "repos/delete-admin-branch-protection",
      "repos/get-pull-request-review-protection",
      "repos/update-pull-request-review-protection",
      "repos/delete-pull-request-review-protection",
      "repos/get-commit-signature-protection",
      "repos/create-commit-signature-protection",
      "repos/delete-commit-signature-protection",
      "repos/get-status-checks-protection",
      "repos/update-status-check-protection",
      "repos/remove-status-check-protection",
      "repos/get-all-status-check-contexts", "repos/add-status-check-contexts",
      "repos/set-status-check-contexts", "repos/remove-status-check-contexts",
      "repos/get-access-restrictions", "repos/delete-access-restrictions",
      "repos/get-apps-with-access-to-protected-branch",
      "repos/add-app-access-restrictions", "repos/set-app-access-restrictions",
      "repos/remove-app-access-restrictions",
      "repos/get-teams-with-access-to-protected-branch",
      "repos/add-team-access-restrictions", "repos/set-team-access-restrictions",
      "repos/remove-team-access-restrictions",
      "repos/get-users-with-access-to-protected-branch",
      "repos/add-user-access-restrictions", "repos/set-user-access-restrictions",
      "repos/remove-user-access-restrictions", "repos/rename-branch",
      "checks/create", "checks/get", "checks/update", "checks/list-annotations",
      "checks/rerequest-run", "checks/create-suite",
      "checks/set-suites-preferences", "checks/get-suite",
      "checks/list-for-suite", "checks/rerequest-suite",
      "code-scanning/list-alerts-for-repo", "code-scanning/get-alert",
      "code-scanning/update-alert", "code-scanning/list-alert-instances",
      "code-scanning/list-recent-analyses", "code-scanning/get-analysis",
      "code-scanning/delete-analysis", "code-scanning/list-codeql-databases",
      "code-scanning/get-codeql-database",
      "code-scanning/delete-codeql-database",
      "code-scanning/create-variant-analysis",
      "code-scanning/get-variant-analysis",
      "code-scanning/get-variant-analysis-repo-task",
      "code-scanning/get-default-setup", "code-scanning/update-default-setup",
      "code-scanning/upload-sarif", "code-scanning/get-sarif",
      "code-security/get-configuration-for-repository",
      "repos/codeowners-errors",
      "codespaces/list-in-repository-for-authenticated-user",
      "codespaces/create-with-repo-for-authenticated-user",
      "codespaces/list-devcontainers-in-repository-for-authenticated-user",
      "codespaces/repo-machines-for-authenticated-user",
      "codespaces/pre-flight-with-repo-for-authenticated-user",
      "codespaces/check-permissions-for-devcontainer",
      "codespaces/list-repo-secrets", "codespaces/get-repo-public-key",
      "codespaces/get-repo-secret", "codespaces/create-or-update-repo-secret",
      "codespaces/delete-repo-secret", "repos/list-collaborators",
      "repos/check-collaborator", "repos/add-collaborator",
      "repos/remove-collaborator", "repos/get-collaborator-permission-level",
      "repos/list-commit-comments-for-repo", "repos/get-commit-comment",
      "repos/update-commit-comment", "repos/delete-commit-comment",
      "reactions/list-for-commit-comment", "reactions/create-for-commit-comment",
      "reactions/delete-for-commit-comment", "repos/list-commits",
      "repos/list-branches-for-head-commit", "repos/list-comments-for-commit",
      "repos/create-commit-comment",
      "repos/list-pull-requests-associated-with-commit", "repos/get-commit",
      "checks/list-for-ref", "checks/list-suites-for-ref",
      "repos/get-combined-status-for-ref", "repos/list-commit-statuses-for-ref",
      "repos/get-community-profile-metrics", "repos/compare-commits",
      "repos/get-content", "repos/create-or-update-file-contents",
      "repos/delete-file", "repos/list-contributors",
      "dependabot/list-alerts-for-repo", "dependabot/get-alert",
      "dependabot/update-alert", "dependabot/list-repo-secrets",
      "dependabot/get-repo-public-key", "dependabot/get-repo-secret",
      "dependabot/create-or-update-repo-secret", "dependabot/delete-repo-secret",
      "dependency-graph/diff-range", "dependency-graph/export-sbom",
      "dependency-graph/create-repository-snapshot", "repos/list-deployments",
      "repos/create-deployment", "repos/get-deployment",
      "repos/delete-deployment", "repos/list-deployment-statuses",
      "repos/create-deployment-status", "repos/get-deployment-status",
      "repos/create-dispatch-event", "repos/get-all-environments",
      "repos/get-environment", "repos/create-or-update-environment",
      "repos/delete-an-environment", "repos/list-deployment-branch-policies",
      "repos/create-deployment-branch-policy",
      "repos/get-deployment-branch-policy",
      "repos/update-deployment-branch-policy",
      "repos/delete-deployment-branch-policy",
      "repos/get-all-deployment-protection-rules",
      "repos/create-deployment-protection-rule",
      "repos/list-custom-deployment-rule-integrations",
      "repos/get-custom-deployment-protection-rule",
      "repos/disable-deployment-protection-rule",
      "actions/list-environment-secrets", "actions/get-environment-public-key",
      "actions/get-environment-secret",
      "actions/create-or-update-environment-secret",
      "actions/delete-environment-secret", "actions/list-environment-variables",
      "actions/create-environment-variable", "actions/get-environment-variable",
      "actions/update-environment-variable",
      "actions/delete-environment-variable", "activity/list-repo-events",
      "repos/list-forks", "repos/create-fork", "git/create-blob", "git/get-blob",
      "git/create-commit", "git/get-commit", "git/list-matching-refs",
      "git/get-ref", "git/create-ref", "git/update-ref", "git/delete-ref",
      "git/create-tag", "git/get-tag", "git/create-tree", "git/get-tree",
      "repos/list-webhooks", "repos/create-webhook", "repos/get-webhook",
      "repos/update-webhook", "repos/delete-webhook",
      "repos/get-webhook-config-for-repo",
      "repos/update-webhook-config-for-repo", "repos/list-webhook-deliveries",
      "repos/get-webhook-delivery", "repos/redeliver-webhook-delivery",
      "repos/ping-webhook", "repos/test-push-webhook",
      "migrations/get-import-status", "migrations/start-import",
      "migrations/update-import", "migrations/cancel-import",
      "migrations/get-commit-authors", "migrations/map-commit-author",
      "migrations/get-large-files", "migrations/set-lfs-preference",
      "apps/get-repo-installation", "interactions/get-restrictions-for-repo",
      "interactions/set-restrictions-for-repo",
      "interactions/remove-restrictions-for-repo", "repos/list-invitations",
      "repos/update-invitation", "repos/delete-invitation",
      "issues/list-for-repo", "issues/create", "issues/list-comments-for-repo",
      "issues/get-comment", "issues/update-comment", "issues/delete-comment",
      "reactions/list-for-issue-comment", "reactions/create-for-issue-comment",
      "reactions/delete-for-issue-comment", "issues/list-events-for-repo",
      "issues/get-event", "issues/get", "issues/update", "issues/add-assignees",
      "issues/remove-assignees", "issues/check-user-can-be-assigned-to-issue",
      "issues/list-comments", "issues/create-comment", "issues/list-events",
      "issues/list-labels-on-issue", "issues/add-labels", "issues/set-labels",
      "issues/remove-all-labels", "issues/remove-label", "issues/lock",
      "issues/unlock", "reactions/list-for-issue", "reactions/create-for-issue",
      "reactions/delete-for-issue", "issues/list-events-for-timeline",
      "repos/list-deploy-keys", "repos/create-deploy-key",
      "repos/get-deploy-key", "repos/delete-deploy-key",
      "issues/list-labels-for-repo", "issues/create-label", "issues/get-label",
      "issues/update-label", "issues/delete-label", "repos/list-languages",
      "licenses/get-for-repo", "repos/merge-upstream", "repos/merge",
      "issues/list-milestones", "issues/create-milestone",
      "issues/get-milestone", "issues/update-milestone",
      "issues/delete-milestone", "issues/list-labels-for-milestone",
      "activity/list-repo-notifications-for-authenticated-user",
      "activity/mark-repo-notifications-as-read", "repos/get-pages",
      "repos/create-pages-site", "repos/update-information-about-pages-site",
      "repos/delete-pages-site", "repos/list-pages-builds",
      "repos/request-pages-build", "repos/get-latest-pages-build",
      "repos/get-pages-build", "repos/create-pages-deployment",
      "repos/get-pages-deployment", "repos/cancel-pages-deployment",
      "repos/get-pages-health-check",
      "repos/check-private-vulnerability-reporting",
      "repos/enable-private-vulnerability-reporting",
      "repos/disable-private-vulnerability-reporting", "projects/list-for-repo",
      "projects/create-for-repo", "repos/get-custom-properties-values",
      "repos/create-or-update-custom-properties-values", "pulls/list",
      "pulls/create", "pulls/list-review-comments-for-repo",
      "pulls/get-review-comment", "pulls/update-review-comment",
      "pulls/delete-review-comment",
      "reactions/list-for-pull-request-review-comment",
      "reactions/create-for-pull-request-review-comment",
      "reactions/delete-for-pull-request-comment", "pulls/get", "pulls/update",
      "codespaces/create-with-pr-for-authenticated-user",
      "pulls/list-review-comments", "pulls/create-review-comment",
      "pulls/create-reply-for-review-comment", "pulls/list-commits",
      "pulls/list-files", "pulls/check-if-merged", "pulls/merge",
      "pulls/list-requested-reviewers", "pulls/request-reviewers",
      "pulls/remove-requested-reviewers", "pulls/list-reviews",
      "pulls/create-review", "pulls/get-review", "pulls/update-review",
      "pulls/delete-pending-review", "pulls/list-comments-for-review",
      "pulls/dismiss-review", "pulls/submit-review", "pulls/update-branch",
      "repos/get-readme", "repos/get-readme-in-directory", "repos/list-releases",
      "repos/create-release", "repos/get-release-asset",
      "repos/update-release-asset", "repos/delete-release-asset",
      "repos/generate-release-notes", "repos/get-latest-release",
      "repos/get-release-by-tag", "repos/get-release", "repos/update-release",
      "repos/delete-release", "repos/list-release-assets",
      "repos/upload-release-asset", "reactions/list-for-release",
      "reactions/create-for-release", "reactions/delete-for-release",
      "repos/get-branch-rules", "repos/get-repo-rulesets",
      "repos/create-repo-ruleset", "repos/get-repo-rule-suites",
      "repos/get-repo-rule-suite", "repos/get-repo-ruleset",
      "repos/update-repo-ruleset", "repos/delete-repo-ruleset",
      "secret-scanning/list-alerts-for-repo", "secret-scanning/get-alert",
      "secret-scanning/update-alert", "secret-scanning/list-locations-for-alert",
      "secret-scanning/create-push-protection-bypass",
      "security-advisories/list-repository-advisories",
      "security-advisories/create-repository-advisory",
      "security-advisories/create-private-vulnerability-report",
      "security-advisories/get-repository-advisory",
      "security-advisories/update-repository-advisory",
      "security-advisories/create-repository-advisory-cve-request",
      "security-advisories/create-fork", "activity/list-stargazers-for-repo",
      "repos/get-code-frequency-stats", "repos/get-commit-activity-stats",
      "repos/get-contributors-stats", "repos/get-participation-stats",
      "repos/get-punch-card-stats", "repos/create-commit-status",
      "activity/list-watchers-for-repo", "activity/get-repo-subscription",
      "activity/set-repo-subscription", "activity/delete-repo-subscription",
      "repos/list-tags", "repos/list-tag-protection",
      "repos/create-tag-protection", "repos/delete-tag-protection",
      "repos/download-tarball-archive", "repos/list-teams",
      "repos/get-all-topics", "repos/replace-all-topics", "repos/get-clones",
      "repos/get-top-paths", "repos/get-top-referrers", "repos/get-views",
      "repos/transfer", "repos/check-vulnerability-alerts",
      "repos/enable-vulnerability-alerts", "repos/disable-vulnerability-alerts",
      "repos/download-zipball-archive", "repos/create-using-template",
      "repos/list-public", "search/code", "search/commits",
      "search/issues-and-pull-requests", "search/labels", "search/repos",
      "search/topics", "search/users", "teams/get-legacy", "teams/update-legacy",
      "teams/delete-legacy", "teams/list-discussions-legacy",
      "teams/create-discussion-legacy", "teams/get-discussion-legacy",
      "teams/update-discussion-legacy", "teams/delete-discussion-legacy",
      "teams/list-discussion-comments-legacy",
      "teams/create-discussion-comment-legacy",
      "teams/get-discussion-comment-legacy",
      "teams/update-discussion-comment-legacy",
      "teams/delete-discussion-comment-legacy",
      "reactions/list-for-team-discussion-comment-legacy",
      "reactions/create-for-team-discussion-comment-legacy",
      "reactions/list-for-team-discussion-legacy",
      "reactions/create-for-team-discussion-legacy",
      "teams/list-pending-invitations-legacy", "teams/list-members-legacy",
      "teams/get-member-legacy", "teams/add-member-legacy",
      "teams/remove-member-legacy", "teams/get-membership-for-user-legacy",
      "teams/add-or-update-membership-for-user-legacy",
      "teams/remove-membership-for-user-legacy", "teams/list-projects-legacy",
      "teams/check-permissions-for-project-legacy",
      "teams/add-or-update-project-permissions-legacy",
      "teams/remove-project-legacy", "teams/list-repos-legacy",
      "teams/check-permissions-for-repo-legacy",
      "teams/add-or-update-repo-permissions-legacy", "teams/remove-repo-legacy",
      "teams/list-child-legacy", "users/get-authenticated",
      "users/update-authenticated", "users/list-blocked-by-authenticated-user",
      "users/check-blocked", "users/block", "users/unblock",
      "codespaces/list-for-authenticated-user",
      "codespaces/create-for-authenticated-user",
      "codespaces/list-secrets-for-authenticated-user",
      "codespaces/get-public-key-for-authenticated-user",
      "codespaces/get-secret-for-authenticated-user",
      "codespaces/create-or-update-secret-for-authenticated-user",
      "codespaces/delete-secret-for-authenticated-user",
      "codespaces/list-repositories-for-secret-for-authenticated-user",
      "codespaces/set-repositories-for-secret-for-authenticated-user",
      "codespaces/add-repository-for-secret-for-authenticated-user",
      "codespaces/remove-repository-for-secret-for-authenticated-user",
      "codespaces/get-for-authenticated-user",
      "codespaces/update-for-authenticated-user",
      "codespaces/delete-for-authenticated-user",
      "codespaces/export-for-authenticated-user",
      "codespaces/get-export-details-for-authenticated-user",
      "codespaces/codespace-machines-for-authenticated-user",
      "codespaces/publish-for-authenticated-user",
      "codespaces/start-for-authenticated-user",
      "codespaces/stop-for-authenticated-user",
      "packages/list-docker-migration-conflicting-packages-for-authenticated-user",
      "users/set-primary-email-visibility-for-authenticated-user",
      "users/list-emails-for-authenticated-user",
      "users/add-email-for-authenticated-user",
      "users/delete-email-for-authenticated-user",
      "users/list-followers-for-authenticated-user",
      "users/list-followed-by-authenticated-user",
      "users/check-person-is-followed-by-authenticated", "users/follow",
      "users/unfollow", "users/list-gpg-keys-for-authenticated-user",
      "users/create-gpg-key-for-authenticated-user",
      "users/get-gpg-key-for-authenticated-user",
      "users/delete-gpg-key-for-authenticated-user",
      "apps/list-installations-for-authenticated-user",
      "apps/list-installation-repos-for-authenticated-user",
      "apps/add-repo-to-installation-for-authenticated-user",
      "apps/remove-repo-from-installation-for-authenticated-user",
      "interactions/get-restrictions-for-authenticated-user",
      "interactions/set-restrictions-for-authenticated-user",
      "interactions/remove-restrictions-for-authenticated-user",
      "issues/list-for-authenticated-user",
      "users/list-public-ssh-keys-for-authenticated-user",
      "users/create-public-ssh-key-for-authenticated-user",
      "users/get-public-ssh-key-for-authenticated-user",
      "users/delete-public-ssh-key-for-authenticated-user",
      "apps/list-subscriptions-for-authenticated-user",
      "apps/list-subscriptions-for-authenticated-user-stubbed",
      "orgs/list-memberships-for-authenticated-user",
      "orgs/get-membership-for-authenticated-user",
      "orgs/update-membership-for-authenticated-user",
      "migrations/list-for-authenticated-user",
      "migrations/start-for-authenticated-user",
      "migrations/get-status-for-authenticated-user",
      "migrations/get-archive-for-authenticated-user",
      "migrations/delete-archive-for-authenticated-user",
      "migrations/unlock-repo-for-authenticated-user",
      "migrations/list-repos-for-authenticated-user",
      "orgs/list-for-authenticated-user",
      "packages/list-packages-for-authenticated-user",
      "packages/get-package-for-authenticated-user",
      "packages/delete-package-for-authenticated-user",
      "packages/restore-package-for-authenticated-user",
      "packages/get-all-package-versions-for-package-owned-by-authenticated-user",
      "packages/get-package-version-for-authenticated-user",
      "packages/delete-package-version-for-authenticated-user",
      "packages/restore-package-version-for-authenticated-user",
      "projects/create-for-authenticated-user",
      "users/list-public-emails-for-authenticated-user",
      "repos/list-for-authenticated-user", "repos/create-for-authenticated-user",
      "repos/list-invitations-for-authenticated-user",
      "repos/accept-invitation-for-authenticated-user",
      "repos/decline-invitation-for-authenticated-user",
      "users/list-social-accounts-for-authenticated-user",
      "users/add-social-account-for-authenticated-user",
      "users/delete-social-account-for-authenticated-user",
      "users/list-ssh-signing-keys-for-authenticated-user",
      "users/create-ssh-signing-key-for-authenticated-user",
      "users/get-ssh-signing-key-for-authenticated-user",
      "users/delete-ssh-signing-key-for-authenticated-user",
      "activity/list-repos-starred-by-authenticated-user",
      "activity/check-repo-is-starred-by-authenticated-user",
      "activity/star-repo-for-authenticated-user",
      "activity/unstar-repo-for-authenticated-user",
      "activity/list-watched-repos-for-authenticated-user",
      "teams/list-for-authenticated-user", "users/get-by-id", "users/list",
      "users/get-by-username", "users/list-attestations",
      "packages/list-docker-migration-conflicting-packages-for-user",
      "activity/list-events-for-authenticated-user",
      "activity/list-org-events-for-authenticated-user",
      "activity/list-public-events-for-user", "users/list-followers-for-user",
      "users/list-following-for-user", "users/check-following-for-user",
      "gists/list-for-user", "users/list-gpg-keys-for-user",
      "users/get-context-for-user", "apps/get-user-installation",
      "users/list-public-keys-for-user", "orgs/list-for-user",
      "packages/list-packages-for-user", "packages/get-package-for-user",
      "packages/delete-package-for-user", "packages/restore-package-for-user",
      "packages/get-all-package-versions-for-package-owned-by-user",
      "packages/get-package-version-for-user",
      "packages/delete-package-version-for-user",
      "packages/restore-package-version-for-user", "projects/list-for-user",
      "activity/list-received-events-for-user",
      "activity/list-received-public-events-for-user",
      // "repos/list-for-user",
      "billing/get-github-actions-billing-user",
      "billing/get-github-packages-billing-user",
      "billing/get-shared-storage-billing-user",
      "users/list-social-accounts-for-user",
      "users/list-ssh-signing-keys-for-user",
      "activity/list-repos-starred-by-user",
      "activity/list-repos-watched-by-user", "meta/get-all-versions",
      "meta/get-zen", "branch-protection-configuration/disabled",
      "branch-protection-configuration/enabled",
      "branch-protection-rule/created", "branch-protection-rule/deleted",
      "branch-protection-rule/edited", "check-run/completed",
      "check-run/created", "check-run/requested-action", "check-run/rerequested",
      "check-suite/completed", "check-suite/requested",
      "check-suite/rerequested", "code-scanning-alert/appeared-in-branch",
      "code-scanning-alert/closed-by-user", "code-scanning-alert/created",
      "code-scanning-alert/fixed", "code-scanning-alert/reopened",
      "code-scanning-alert/reopened-by-user", "commit-comment/created", "create",
      "custom-property/created", "custom-property/deleted",
      "custom-property/updated", "custom-property-values/updated", "delete",
      "dependabot-alert/auto-dismissed", "dependabot-alert/auto-reopened",
      "dependabot-alert/created", "dependabot-alert/dismissed",
      "dependabot-alert/fixed", "dependabot-alert/reintroduced",
      "dependabot-alert/reopened", "deploy-key/created", "deploy-key/deleted",
      "deployment/created", "deployment-protection-rule/requested",
      "deployment-review/approved", "deployment-review/rejected",
      "deployment-review/requested", "deployment-status/created",
      "discussion/answered", "discussion/category-changed", "discussion/closed",
      "discussion-comment/created", "discussion-comment/deleted",
      "discussion-comment/edited", "discussion/created", "discussion/deleted",
      "discussion/edited", "discussion/labeled", "discussion/locked",
      "discussion/pinned", "discussion/reopened", "discussion/transferred",
      "discussion/unanswered", "discussion/unlabeled", "discussion/unlocked",
      "discussion/unpinned", "fork", "github-app-authorization/revoked",
      "gollum", "installation/created", "installation/deleted",
      "installation/new-permissions-accepted", "installation-repositories/added",
      "installation-repositories/removed", "installation/suspend",
      "installation-target/renamed", "installation/unsuspend",
      "issue-comment/created", "issue-comment/deleted", "issue-comment/edited",
      "issues/assigned", "issues/closed", "issues/deleted",
      "issues/demilestoned", "issues/edited", "issues/labeled", "issues/locked",
      "issues/milestoned", "issues/opened", "issues/pinned", "issues/reopened",
      "issues/transferred", "issues/unassigned", "issues/unlabeled",
      "issues/unlocked", "issues/unpinned", "label/created", "label/deleted",
      "label/edited", "marketplace-purchase/cancelled",
      "marketplace-purchase/changed", "marketplace-purchase/pending-change",
      "marketplace-purchase/pending-change-cancelled",
      "marketplace-purchase/purchased", "member/added", "member/edited",
      "member/removed", "membership/added", "membership/removed",
      "merge-group/checks-requested", "merge-group/destroyed", "meta/deleted",
      "milestone/closed", "milestone/created", "milestone/deleted",
      "milestone/edited", "milestone/opened", "org-block/blocked",
      "org-block/unblocked", "organization/deleted", "organization/member-added",
      "organization/member-invited", "organization/member-removed",
      "organization/renamed", "package/published", "package/updated",
      "page-build", "personal-access-token-request/approved",
      "personal-access-token-request/cancelled",
      "personal-access-token-request/created",
      "personal-access-token-request/denied", "ping", "project-card/converted",
      "project-card/created", "project-card/deleted", "project-card/edited",
      "project-card/moved", "project/closed", "project-column/created",
      "project-column/deleted", "project-column/edited", "project-column/moved",
      "project/created", "project/deleted", "project/edited", "project/reopened",
      "projects-v2/closed", "projects-v2/created", "projects-v2/deleted",
      "projects-v2/edited", "projects-v2-item/archived",
      "projects-v2-item/converted", "projects-v2-item/created",
      "projects-v2-item/deleted", "projects-v2-item/edited",
      "projects-v2-item/reordered", "projects-v2-item/restored",
      "projects-v2/reopened", "projects-v2-status-update/created",
      "projects-v2-status-update/deleted", "projects-v2-status-update/edited",
      "public", "pull-request/assigned", "pull-request/auto-merge-disabled",
      "pull-request/auto-merge-enabled", "pull-request/closed",
      "pull-request/converted-to-draft", "pull-request/demilestoned",
      "pull-request/dequeued", "pull-request/edited", "pull-request/enqueued",
      "pull-request/labeled", "pull-request/locked", "pull-request/milestoned",
      "pull-request/opened", "pull-request/ready-for-review",
      "pull-request/reopened", "pull-request-review-comment/created",
      "pull-request-review-comment/deleted",
      "pull-request-review-comment/edited", "pull-request-review/dismissed",
      "pull-request-review/edited", "pull-request/review-request-removed",
      "pull-request/review-requested", "pull-request-review/submitted",
      "pull-request-review-thread/resolved",
      "pull-request-review-thread/unresolved", "pull-request/synchronize",
      "pull-request/unassigned", "pull-request/unlabeled",
      "pull-request/unlocked", "push", "registry-package/published",
      "registry-package/updated", "release/created", "release/deleted",
      "release/edited", "release/prereleased", "release/published",
      "release/released", "release/unpublished", "repository-advisory/published",
      "repository-advisory/reported", "repository/archived",
      "repository/created", "repository/deleted",
      "repository-dispatch/sample.collected", "repository/edited",
      "repository-import", "repository/privatized", "repository/publicized",
      "repository/renamed", "repository-ruleset/created",
      "repository-ruleset/deleted", "repository-ruleset/edited",
      "repository/transferred", "repository/unarchived",
      "repository-vulnerability-alert/create",
      "repository-vulnerability-alert/dismiss",
      "repository-vulnerability-alert/reopen",
      "repository-vulnerability-alert/resolve", "secret-scanning-alert/created",
      "secret-scanning-alert-location/created",
      "secret-scanning-alert/publicly-leaked", "secret-scanning-alert/reopened",
      "secret-scanning-alert/resolved", "secret-scanning-alert/validated",
      "security-advisory/published", "security-advisory/updated",
      "security-advisory/withdrawn", "security-and-analysis",
      "sponsorship/cancelled", "sponsorship/created", "sponsorship/edited",
      "sponsorship/pending-cancellation", "sponsorship/pending-tier-change",
      "sponsorship/tier-changed", "star/created", "star/deleted", "status",
      "sub-issues/parent-issue-added", "sub-issues/parent-issue-removed",
      "sub-issues/sub-issue-added", "sub-issues/sub-issue-removed", "team-add",
      "team/added-to-repository", "team/created", "team/deleted", "team/edited",
      "team/removed-from-repository", "watch/started", "workflow-dispatch",
      "workflow-job/completed", "workflow-job/in-progress",
      "workflow-job/queued", "workflow-job/waiting", "workflow-run/completed",
      "workflow-run/in-progress", "workflow-run/requested",
    ])
  {
    Ok(_) -> Nil
    Error(reason) -> io.print(snag.pretty_print(reason))
  }
}
