name = "netlify"
version = "1.0.0"
target = "javascript"
description = "Gleam client for the netlify API"
licences = ["Apache-2.0"]
repository = { type = "github", user = "midas-framework", repo = "midas_sdk", path = "sdks/netlify" }
links = []


[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
snag = ">= 1.1.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
midas = ">= 1.4.1 and < 2.0.0"
gleam_json = ">= 3.0.1 and < 4.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 1.4.0"
oas_generator = ">= 1.6.1 and < 2.0.0"

